# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Standard values.yaml can be found at: 
# https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml
controller:
  tag: "2.300"
  containerEnv:
    - name: PROJECT_ID
      valueFrom:
        secretKeyRef:
            name: jenkins-k8s-config
            key: project_id
    - name: GITHUB_REPO
      valueFrom:
        secretKeyRef:
            name: github-secrets
            key: github_repo
    - name: GITHUB_USERNAME
      valueFrom:
        secretKeyRef:
            name: github-secrets
            key: github_username
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
            name: github-secrets
            key: github_token
    - name: jenkins_tf_ksa
      valueFrom:
        secretKeyRef:
            name: jenkins-k8s-config
            key: jenkins_tf_ksa
  servicePort: 80
  serviceType: LoadBalancer
  installPlugins:
      # - blueocean-dashboard:latest # ðŸ’ D-BlueOcean ï¸  
      - checks-api:1.7.4 # checks customization
      # - pipeline-stage-view:2.24 # ðŸ’ D-Pipeline
      # - ssh-credentials:latest #    ðŸ’ D-Credentials
      - popper2-api:2.11.5-2 # JS tooltip functionality
      # - structs:latest ðŸ’ D-Credentials
      # - blueocean-core-js:latest # ðŸ’ D-BlueOcean
      # - momentjs:latest # âŒ
      # - blueocean-personalization:latest ðŸ’ D-BlueOcean
      - sshd:3.242.va_db_9da_b_26a_c3 #  âŒ 
      - git-client:3.11.0 # allows git operations
      # - workflow-durable-task-step:latest ðŸ’ D-Pipeline;aka-p.nodes&processes
      # - workflow-cps-global-lib:latest âŒDeprecated.Newâ¬‡ï¸
      # - pipeline-groovy-lib:598.vcd66b_a_336510 ðŸ’ D-Pipeline
      # - popper-api:latest âŒ 
      # - workflow-basic-steps:latest ðŸ’ D-Pipeline
      # - pipeline-graph-analysis:195.v5812d95a_a_2f9 âœ”ï¸ 
      # - blueocean-pipeline-editor:latest ðŸ’ D-BlueOcean
      - workflow-aggregator:590.v6a_d052e5a_a_b_5 # aka Pipelines
      - plain-credentials:1.8
      - kubernetes-credentials:0.9.0
      - favorite:2.4.1
      # - blueocean-i18n:latestðŸ’ D-BlueOcean
      - workflow-support:833.va_1c71061486b_
      - github:1.34
      - configuration-as-code:1414.v878271fc496f
      # - display-url-api:2.3.6 #ï¸ âœ”ï¸
      # - blueocean-config:latest ðŸ’ D-BlueOcean
      # - jenkins-design-language:latest  ðŸ’ D-BlueOcean
      # - bootstrap4-api:latest ðŸ’ D?
      # - bouncycastle-api:latest ðŸ’ D?
      # - durable-task:latest ðŸ’ D?
      # - blueocean-git-pipeline:latest ðŸ’ D-BlueOcean
      # - blueocean-github-pipeline:1.25.5 ðŸ’ D-BlueOcean
      # - font-awesome-api:latest ðŸ’ D?
      # - caffeine-api:latest ðŸ’ D?
      # - jackson2-api:latest ðŸ’ D?
      # - htmlpublisher:1.30 # ðŸ’ D?
      # - workflow-api:latest ðŸ’ D?
      # - pipeline-stage-step:latest ðŸ’ D-Pipeline
      - git:4.10.2
      # - workflow-job:latest ðŸ’ D-Pipeline
      - blueocean-pipeline-scm-api:1.25.5
      - pipeline-stage-tags-metadata:2.2114.v2654ca_721309
      # - jira:latest  âŒ
      # - matrix-project:latest  âœ”ï¸ 
      # - jsch:latest  ðŸ’ D
      # - lockable-resources:latest  ðŸ’ D
      # - variant:latest ðŸ’ D~?
      # - git-server:latest ðŸ’ D
      # - cloudbees-bitbucket-branch-source:latest âŒ 
      # - trilead-api:latest ðŸ’ D  
      # - scm-api:latest  ðŸ’ D
      # - docker-workflow:latest # âŒ 
      # - pubsub-light:latest ðŸ’ D
      # - jdk-tool:latest âŒ?
      # - branch-api:latest ðŸ’ D?
      # - plugin-util-api:latest ðŸ’ D?
      - authentication-tokens:1.4
      - handlebars:latest # ðŸ’ perhaps-removable
      - pipeline-model-extensions:2.2114.v2654ca_721309 
      - token-macro:308.v4f2b_ed62b_b_16
      # - pipeline-rest-api:latest ðŸ’ D?
      # - blueocean-display-url:latest ðŸ’ D-BlueOcean
      # - jjwt-api:latest ðŸ’ D
      - mailer:438.v02c7f0a_12fa_4
      # - blueocean-autofavorite:latest  ðŸ’ D-BlueOcean
      # - blueocean-commons:latest  ðŸ’ D-BlueOcean
      - blueocean:1.25.5
      - command-launcher:80.v4a_97f2027398
      # - blueocean-rest:latest  ðŸ’ D-BlueOcean
      - kubernetes:1.31.3
      # - apache-httpcomponents-client-4-api:latest ðŸ’ D?
      - cloudbees-folder:6.729.v2b_9d1a_74d673 
      - job-dsl:1.81
      # - blueocean-bitbucket-pipeline:latest  ðŸ’ D-BlueOcean
      # - docker-commons:latest âŒ
      # - bootstrap5-api:latest ðŸ’ D-BlueOcean
      # - blueocean-jira:latest  ðŸ’ D-BlueOcean Optional
      # - pipeline-milestone-step:latest ðŸ’ D-BlueOcean
      # - blueocean-pipeline-api-impl:latest ðŸ’ D-BlueOcean
      # - pipeline-model-api:latest ðŸ’ D?
      # - pipeline-model-definition:latest ðŸ’ D-Pipeline
      # - echarts-api:latest âœ”ï¸ 
      # - docker-custom-build-environment:latest  âŒ 
      # - handy-uri-templates-2-api:latest ðŸ’ D?
      # - kubernetes-client-api:latest ðŸ’ D
      # - github-branch-source:latest âŒ 
      # - blueocean-jwt:latest  ðŸ’ D-BlueOcean 
      # - pipeline-input-step:latest ðŸ’ D-Pipeline
      # - github-api:latest ðŸ’ D
      - junit:1119.1121.vc43d0fc45561
      - credentials-binding:latest
      - workflow-scm-step:400.v6b_89a_1317c9a_
      - pipeline-build-step:2.18
      - ace-editor:1.1
      # - blueocean-web:latest  ðŸ’ D-BlueOcean 
      # - workflow-step-api:latest ðŸ’ D?
      - sse-gateway:1.25
      - credentials:1139.veb_9579fca_33b_
      # - okhttp-api:latest ðŸ’ D?
      # - snakeyaml-api:latest ðŸ’ D?
      # - blueocean-rest-impl:latest  ðŸ’ D-BlueOcean 
      # - metrics:latest ðŸ’ D?
      # - blueocean-events:latest  ðŸ’ D-BlueOcean 
      # - workflow-cps:latest  ðŸ’ D-Pipeline
      # - jquery3-api:latest  ðŸ’ D?
      # - script-security: âœ”ï¸
      # - workflow-multibranch:latest ðŸ’ D-Pipeline
  JCasC:
    enabled: true
    configScripts:
        cloud: |
            jenkins:
                clouds:
                    - kubernetes:
                        name: "gke-executors"
                        serverUrl: "https://kubernetes.default"
                        jenkinsTunnel: "jenkins-agent:50000"
                        jenkinsUrl: "http://jenkins:80"
                        skipTlsVerify: true
                        namespace: "default"
                        templates:
                            - name: "jenkins-jnlp"
                              namespace: "default"
                              nodeUsageMode: NORMAL
                              label: "jnlp-exec"
                              containers:
                                - name: "jnlp"
                                  image: "jenkins/jnlp-slave"
                                  alwaysPullImage: false
                                  workingDir: "/home/jenkins/agent"
                                  ttyEnabled: true
                                  command: ""
                                  args: ""
                                  resourceRequestCpu: "500m"
                                  resourceLimitCpu: "1000m"
                                  resourceRequestMemory: "1Gi"
                                  resourceLimitMemory: "2Gi"
                              volumes:
                                - emptyDirVolume:
                                    memory: false
                                    mountPath: "/tmp"
                              idleMinutes: "1"
                              activeDeadlineSeconds: "120"
                              slaveConnectTimeout: "1000"
                            - name: "terraform"
                              namespace: "default"
                              nodeUsageMode: NORMAL
                              serviceAccount: ${jenkins_tf_ksa}
                              label: "terraform-exec"
                              containers:
                                - name: "terraform"
                                  image: "hashicorp/terraform:0.12.29"
                                  alwaysPullImage: false
                                  workingDir: "/home/jenkins/agent"
                                  ttyEnabled: true
                                  command: "/bin/sh -c"
                                  args: "cat"
                                  resourceRequestCpu: "100m"
                                  resourceLimitCpu: "500m"
                                  resourceRequestMemory: "500Mi"
                                  resourceLimitMemory: "1Gi"
                              volumes:
                                - emptyDirVolume:
                                    memory: false
                                    mountPath: "/tmp"
                              podRetention: "never"
                              activeDeadlineSeconds: "300"
                              slaveConnectTimeout: "1000"
        credentials: |
            credentials:
                system:
                    domainCredentials:
                    - credentials:
                        - usernamePassword:
                            scope: GLOBAL
                            id: "github-token"
                            username: ${GITHUB_USERNAME}
                            password: ${GITHUB_TOKEN}
                            description: "Github personal token"
        init-jobs: |
            jobs:
              - script: >
                    multibranchPipelineJob('terraform-jenkins-create-env') {
                        factory {
                        workflowBranchProjectFactory {
                            scriptPath('pipelines/environments/Jenkinsfile')
                        }
                        }
                        branchSources {
                        github {
                            id('13374160')
                            scanCredentialsId('github-token')
                            repoOwner("${GITHUB_USERNAME}")
                            repository("${GITHUB_REPO}")
                            buildOriginBranch(true)
                            buildOriginPRMerge(true)
                            includes("dev prod PR*")
                        }
                        }
                        orphanedItemStrategy {
                        discardOldItems {
                            numToKeep(10)
                        }
                        }
                        triggers {
                        periodic(1)
                        }
                    }
